name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: SETUP - Semantic Version
        id: read-properties
        uses: juliangruber/read-file-action@v1
        with:
          path: ./Sources/Properties.proj
        
      - name: SETUP - Semantic Version
        id: get-semantic-version
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ steps.read-properties.outputs.content }}
          regex: '<Version>(.*?)</Version>'  
                      
      - name: SETUP - QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: DOCKER - Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          registry: silvester.jfrog.io
        
      - name: SETUP - Docker
        uses: docker/setup-buildx-action@v1
        
      - name: DOCKER - Build & Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            artifactoryUsername=${{ secrets.ARTIFACTORY_USERNAME }}
            artifactoryPassword=${{ secrets.ARTIFACTORY_PASSWORD }}
          tags: |
            silvester.jfrog.io/silvester-docker/pathfinder-reference-web:${{ steps.get-semantic-version.outputs.group1 }}
            silvester.jfrog.io/silvester-docker/pathfinder-reference-web:latest